---
toc: true
toc-location: left
comments: false
---

::: {.resume}
# Curriculum Vitae
## Work Experience
### Present
#### System Analyst
##### Pet Arabia Co. W.L.L , Bahrain
##### Aug 2021 - **Present**

Building the IT infrastructure of the company, and furthering its growth in the GCC.

#### ML Engineer & Associate Business Manager (Remote)
##### plantOS W.L.L, Malaysia & Bahrain
##### Oct 2019 - **Present**
Developing ML algorithms to derive insights on accelerating yield for farmers, and eliminating diseases that plague them. As well as growing the agri-tech business in the GCC, to build a strong base for the company on the world stage.

### 2021
#### AI Instructor (Hybrid & Part-Time)
##### Go My Code, Bahrain
##### Mar 2021 - Feb 2022


#### Machine Learning Engineer
##### HakTrakNetworks, Bahrain
##### May 2021 - Jul 2021

- Spearheading the ML capabilities for the startup in the field of Cyber Security.
- Our team successfully built and operated an intrusion detection system to prevent cyber attacks, from headquarters.

### 2020
#### National Support Manager | Information Management
##### AIESEC in Bahrain
##### Apr 2020 - Jan 2021
- Developed dashboards & data structures with the National Team of AIESEC in Bahrain to track performance and potential growth of the entity more transparently.


#### Local Chapter Vice President | Project Management
##### AIESEC in Bahrain
##### Feb 2020 - Jan 2021
VP of a local chapter for AIESEC in Bahrain. Leading a department to create projects that deliver social impact in the country under the United Nations Sustainable Development Goals.

### 2019
#### Team Leader | Incoming Global Exchange Program
##### AIESEC in Bahrain
##### Feb 2019 - Feb 2020
- Managed teams within the Global Exchange products to connect a group of diverse & talented individuals from around the globe to startups & NGOs in the Kingdom of Bahrain to take on internships, and delivering life-changing experiences in the process.

#### Game Instructor (Part-time)
##### Cleverplay, Bahrain
##### May 2019 - Jun 2019
- Taught kids from years 2-5 and introduced them to world-building using Minecraft at St. Christopher's Primary School.

### 2018
#### Information Technology Officer 
##### The Hive, Bahrain
##### Nov 2018 - Feb 2019

- Worked as a Software Developer. Managed and developed tutorials on Basic Electronics
and Computers aimed at kids and young adults. 
- Accomplishments include --->
    - Further developed a motion tracking software using pose estimation for clients to
    compete in **Mashro3i 2019**.
    - Conducted a Basic Computer workshop for a primary school in Karzakan, Bahrain


#### Machine Learning Intern
##### Suprath Technologies Private Limited, Bangalore, India
##### Jan 2018 - May 2018
- Interned at a Data Science Startup on Customer Care Support.
- Succeeded in creating a sentence generation tool along with a dialog script for a chat-bot using Natural Language Processing to resolve chat queries.

 [Recommendation Letter 🔥]()

## Education
### 2018
#### Acharya Institute of Technology 
##### Bangalore, India
##### Aug 2014 - Jul 2018
- Activities and societies: Member of Nature Watch (2016-2018)
- Voracious Quizzer

### Until 2013
#### Al Noor International School
:::